### ISSUE TITLE
Version 5.x and 6.x doesnt work on php 7.3

### ISSUE THREAD

**Issue by BigOHenry** [contributte/rabbitmq#31]
Version 5.x and 6.x should be compatible with php7.3, but there is a lot of syntax from php7.4. So it doesnt work.

**Comment by paveljanda** [comment]
Thanks, I will update composer.json to require >= 7.4

**Comment by BigOHenry** [comment]
Thank you!

**Comment by f3l1x** [comment]
Done. Closing here.
