### ISSUE TITLE
Bind one queue to exchange with multiple binding keys

### ISSUE THREAD

**Issue by VojtechBuba** [contributte/rabbitmq#59]
Hello RabbitMq supports binding one queue to exchange over multiple binding keys. I am missing this function in this library and i would really appreciate if it can be possible. 

If it is possible, can you tell me how? 

Currently only string value is possible to pass as a value to attribute `routingKey`. 

```neon
	exchanges:
		testExchange:
			connection: default
			type: fanout
			queueBindings:
				testQueue:
					routingKey: testRoutingKey
			# force exchange declare on first exchange operation during request
			# autoCreate: true
```

It would be great if something like this will be possible
```neon
	exchanges:
		testExchange:
			connection: default
			type: fanout
			queueBindings:
				testQueue:
					routingKey: 
						- 'FirstKey.#'
						- 'SecondKey.*'      
			# force exchange declare on first exchange operation during request
			# autoCreate: true
```

**Comment by bckp** [comment]
you can see mallgroup/rabbitmq, there is exactly this implemented :)

**Comment by VojtechBuba** [comment]
https://github.com/contributte/rabbitmq/pull/61
